# Generated by Django 5.2.15 on 2026-07-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analise", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardKpiCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ytd_custo_atual",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "ytd_custo_anterior_equivalente",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "mtd_custo_atual",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "mtd_custo_anterior_equivalente",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "fator_retorno_atual",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "fator_retorno_anterior",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                ("volume_itens_atual", models.IntegerField(default=0)),
                ("volume_itens_anterior", models.IntegerField(default=0)),
                ("dados_mensais_grafico", models.JSONField(default=list)),
                ("ultima_data_processada", models.DateField(blank=True, null=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "dashboard_kpi_compra",
            },
        ),
    ]
