# Generated by Django 5.2.15 on 2026-07-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analise", "0002_dashboardkpicompra"),
    ]

    operations = [
        migrations.CreateModel(
            name="DreMensalConsolidada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.IntegerField(db_index=True)),
                ("mes", models.IntegerField()),
                (
                    "total_receita",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total_custo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "dre_mensal_consolidada",
                "unique_together": {("ano", "mes")},
            },
        ),
    ]
