# Generated by Django 5.2.15 on 2026-08-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analise", "0003_dremensalconsolidada"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovimentoDiario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(db_index=True)),
                ("tipo_venda_id", models.IntegerField(db_index=True)),
                ("tipo_venda_nome", models.CharField(max_length=80)),
                ("qtd_vendas", models.IntegerField(default=0)),
                (
                    "valor_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "movimento_diario",
                "unique_together": {("data", "tipo_venda_id")},
            },
        ),
    ]
