# Generated by Django 5.2.15 on 2026-09-03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analise", "0004_movimentodiario"),
        ("cadastros", "0013_planoconta_codigo_ordenacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovimentoProdutoMensal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ano", models.IntegerField(db_index=True)),
                ("mes", models.PositiveSmallIntegerField()),
                ("unidade_medida_id_origem", models.IntegerField(default=0)),
                ("unidade_sigla", models.CharField(default="SEM UN.", max_length=20)),
                ("receita_bruta", models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ("quantidade", models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "produto",
                    models.ForeignKey(
                        db_column="id_produto",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimentos_mensais",
                        to="cadastros.produto",
                    ),
                ),
            ],
            options={"db_table": "movimento_produto_mensal"},
        ),
        migrations.CreateModel(
            name="StatusMovimentoProdutoMensal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ano", models.IntegerField(db_index=True)),
                ("mes", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("PROCESSANDO", "Processando"), ("PRONTO", "Pronto"), ("FALHA", "Falha")],
                        default="PROCESSANDO",
                        max_length=20,
                    ),
                ),
                ("erro", models.TextField(blank=True, default="")),
                ("ultimo_sucesso_em", models.DateTimeField(blank=True, null=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "status_movimento_produto_mensal"},
        ),
        migrations.AddConstraint(
            model_name="movimentoprodutomensal",
            constraint=models.UniqueConstraint(
                fields=("ano", "mes", "produto", "unidade_medida_id_origem"),
                name="uniq_mov_produto_mes_unidade",
            ),
        ),
        migrations.AddIndex(
            model_name="movimentoprodutomensal",
            index=models.Index(fields=["ano", "mes"], name="idx_mov_prod_ano_mes"),
        ),
        migrations.AddIndex(
            model_name="movimentoprodutomensal",
            index=models.Index(fields=["produto", "ano", "mes"], name="idx_mov_produto_periodo"),
        ),
        migrations.AddConstraint(
            model_name="statusmovimentoprodutomensal",
            constraint=models.UniqueConstraint(fields=("ano", "mes"), name="uniq_status_mov_prod_periodo"),
        ),
        migrations.AddIndex(
            model_name="statusmovimentoprodutomensal",
            index=models.Index(fields=["ano", "status"], name="idx_status_mov_prod_ano"),
        ),
    ]
