# Generated by Django 5.2

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analise", "0005_movimentoprodutomensal_status"),
        ("cadastros", "0013_planoconta_codigo_ordenacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovimentoCompraProdutoMensal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ano", models.IntegerField(db_index=True)),
                ("mes", models.PositiveSmallIntegerField()),
                ("unidade_medida_id_origem", models.IntegerField(default=0)),
                ("unidade_sigla", models.CharField(default="SEM UN.", max_length=20)),
                ("valor_comprado", models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ("quantidade", models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "fornecedor",
                    models.ForeignKey(
                        db_column="id_fornecedor",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimentos_compra_mensais",
                        to="cadastros.fornecedor",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        db_column="id_produto",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimentos_compra_mensais",
                        to="cadastros.produto",
                    ),
                ),
            ],
            options={"db_table": "movimento_compra_produto_mensal"},
        ),
        migrations.CreateModel(
            name="StatusMovimentoCompraProdutoMensal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ano", models.IntegerField(db_index=True)),
                ("mes", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("PROCESSANDO", "Processando"), ("PRONTO", "Pronto"), ("FALHA", "Falha")],
                        default="PROCESSANDO",
                        max_length=20,
                    ),
                ),
                ("erro", models.TextField(blank=True, default="")),
                ("ultimo_sucesso_em", models.DateTimeField(blank=True, null=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "status_movimento_compra_produto_mensal"},
        ),
        migrations.AddConstraint(
            model_name="movimentocompraprodutomensal",
            constraint=models.UniqueConstraint(
                fields=("ano", "mes", "produto", "fornecedor", "unidade_medida_id_origem"),
                name="uniq_mov_compra_prod_mes_fornec_un",
            ),
        ),
        migrations.AddIndex(
            model_name="movimentocompraprodutomensal",
            index=models.Index(fields=["ano", "mes"], name="idx_mov_compra_ano_mes"),
        ),
        migrations.AddIndex(
            model_name="movimentocompraprodutomensal",
            index=models.Index(fields=["produto", "ano", "mes"], name="idx_mov_compra_prod_periodo"),
        ),
        migrations.AddIndex(
            model_name="movimentocompraprodutomensal",
            index=models.Index(fields=["fornecedor", "ano", "mes"], name="idx_mov_compra_forn_periodo"),
        ),
        migrations.AddConstraint(
            model_name="statusmovimentocompraprodutomensal",
            constraint=models.UniqueConstraint(
                fields=("ano", "mes"),
                name="uniq_status_mov_compra_prod_periodo",
            ),
        ),
        migrations.AddIndex(
            model_name="statusmovimentocompraprodutomensal",
            index=models.Index(fields=["ano", "status"], name="idx_status_mov_compra_ano"),
        ),
    ]
