# Generated by Django 5.2.15 on 2026-10-08 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analise", "0010_categoria_venda_quarentena"),
        ("cadastros", "0013_planoconta_codigo_ordenacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusMovimentoCompraProdutoSemanal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semana_inicio", models.DateField(unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROCESSANDO", "Processando"),
                            ("PRONTO", "Pronto"),
                            ("FALHA", "Falha"),
                        ],
                        default="PROCESSANDO",
                        max_length=20,
                    ),
                ),
                ("erro", models.TextField(blank=True, default="")),
                ("ultimo_sucesso_em", models.DateTimeField(blank=True, null=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "status_movimento_compra_produto_semanal",
            },
        ),
        migrations.CreateModel(
            name="MovimentoCompraProdutoDiario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(db_index=True)),
                ("unidade_medida_id_origem", models.IntegerField(default=0)),
                ("unidade_sigla", models.CharField(default="SEM UN.", max_length=20)),
                (
                    "valor_comprado",
                    models.DecimalField(decimal_places=6, default=0, max_digits=24),
                ),
                (
                    "quantidade",
                    models.DecimalField(decimal_places=6, default=0, max_digits=24),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "fornecedor",
                    models.ForeignKey(
                        db_column="id_fornecedor",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadastros.fornecedor",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        db_column="id_produto",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadastros.produto",
                    ),
                ),
            ],
            options={
                "db_table": "movimento_compra_produto_diario",
                "indexes": [
                    models.Index(
                        fields=["produto", "data"], name="idx_mov_compra_prod_dia"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "data",
                            "produto",
                            "fornecedor",
                            "unidade_medida_id_origem",
                        ),
                        name="uniq_mov_compra_prod_dia_for_un",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MovimentoCompraProdutoSemanal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semana_inicio", models.DateField(db_index=True)),
                ("unidade_medida_id_origem", models.IntegerField(default=0)),
                ("unidade_sigla", models.CharField(default="SEM UN.", max_length=20)),
                (
                    "valor_comprado",
                    models.DecimalField(decimal_places=6, default=0, max_digits=24),
                ),
                (
                    "quantidade",
                    models.DecimalField(decimal_places=6, default=0, max_digits=24),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "fornecedor",
                    models.ForeignKey(
                        db_column="id_fornecedor",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadastros.fornecedor",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        db_column="id_produto",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadastros.produto",
                    ),
                ),
            ],
            options={
                "db_table": "movimento_compra_produto_semanal",
                "indexes": [
                    models.Index(
                        fields=["produto", "semana_inicio"],
                        name="idx_mov_compra_prod_sem",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "semana_inicio",
                            "produto",
                            "fornecedor",
                            "unidade_medida_id_origem",
                        ),
                        name="uniq_mov_compra_prod_sem_for_un",
                    )
                ],
            },
        ),
    ]
