# Generated by Django 5.2.15 on 2026-06-05 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StgProdutosNovos",
            fields=[
                (
                    "id_produto",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("gtin", models.CharField(blank=True, default="", max_length=32)),
                ("barras", models.CharField(blank=True, default="", max_length=64)),
                ("nome", models.CharField(max_length=120)),
                (
                    "unidade_comecial",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("custo", models.DecimalField(decimal_places=6, max_digits=18)),
                ("valor_venda", models.DecimalField(decimal_places=6, max_digits=18)),
                ("dt_ultimo_movimento", models.DateField(blank=True, null=True)),
                ("status", models.CharField(blank=True, default="", max_length=30)),
                ("extraido_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "stg_produtos_novos",
            },
        ),
    ]
