# Generated by Django 5.2.15 on 2026-06-05 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integracao", "0002_unidademedida_produto_barras_produto_gtin_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StgClientesNovos",
            fields=[
                (
                    "id_cliente",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("cliente", models.CharField(max_length=120)),
                (
                    "raz_social",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("extraido_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "stg_clientes_novos",
            },
        ),
        migrations.CreateModel(
            name="StgFornecedoresNovos",
            fields=[
                (
                    "id_fornecedor",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("fantasia", models.CharField(max_length=120)),
                (
                    "raz_social",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("dt_cadastro", models.DateField(blank=True, null=True)),
                ("extraido_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "stg_fornecedores_novos",
            },
        ),
    ]
