# Generated by Django 5.2.15 on 2026-06-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integracao", "0003_stgclientesnovos_stgfornecedoresnovos"),
    ]

    operations = [
        migrations.AddField(
            model_name="stgclientesnovos",
            name="hash_md5",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="stgfornecedoresnovos",
            name="hash_md5",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="stgprodutosnovos",
            name="hash_md5",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
