# Generated by Django 5.2.15 on 2026-06-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integracao", "0005_firebirdconnectionconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="stgprodutosnovos",
            name="ncm",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
    ]
