# Generated by Django 5.2.15 on 2026-06-05 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UnidadeMedida",
            fields=[
                (
                    "id_und_medida",
                    models.AutoField(
                        db_column="id_und_medida", primary_key=True, serialize=False
                    ),
                ),
                ("sigla", models.CharField(max_length=10, unique=True)),
                ("descricao", models.CharField(blank=True, default="", max_length=60)),
            ],
            options={
                "db_table": "unidade_medida",
            },
        ),
        migrations.CreateModel(
            name="PlanoConta",
            fields=[
                (
                    "id_conta",
                    models.AutoField(
                        db_column="id_conta", primary_key=True, serialize=False
                    ),
                ),
                ("codigo_hierarquico", models.CharField(max_length=30)),
                ("nome_conta", models.CharField(max_length=120)),
                (
                    "conta_pai",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_conta_pai",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="filhas",
                        to="cadastros.planoconta",
                    ),
                ),
            ],
            options={
                "db_table": "plano_conta",
                "unique_together": {("codigo_hierarquico", "nome_conta")},
            },
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id_produto",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("gtin", models.CharField(blank=True, default="", max_length=32)),
                ("barras", models.CharField(blank=True, default="", max_length=64)),
                ("produto", models.CharField(max_length=120)),
                ("custo", models.DecimalField(decimal_places=6, max_digits=18)),
                ("venda", models.DecimalField(decimal_places=6, max_digits=18)),
                ("status", models.CharField(blank=True, default="", max_length=30)),
                ("markup", models.DecimalField(decimal_places=4, max_digits=10)),
                ("markup_inv", models.DecimalField(decimal_places=4, max_digits=10)),
                ("perda", models.DecimalField(decimal_places=4, max_digits=10)),
                ("ult_mov", models.DateField(blank=True, null=True)),
                ("fisico", models.DecimalField(decimal_places=4, max_digits=10)),
                ("aliqefc", models.CharField(max_length=20)),
                ("cod_g3n", models.IntegerField()),
                ("cod_rel", models.IntegerField()),
                ("operador", models.IntegerField()),
                ("usuario", models.CharField(blank=True, default="", max_length=100)),
                (
                    "categorias",
                    models.ManyToManyField(
                        blank=True,
                        related_name="produtos_vinculados",
                        to="cadastros.planoconta",
                    ),
                ),
                (
                    "id_und_medida",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_und_medida",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="produtos",
                        to="cadastros.unidademedida",
                    ),
                ),
            ],
            options={
                "db_table": "produtos",
            },
        ),
    ]
