# Generated by Django 5.2.15 on 2026-06-05 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodSis",
            fields=[
                (
                    "id_codsis",
                    models.AutoField(
                        db_column="id_codsis", primary_key=True, serialize=False
                    ),
                ),
                ("nome", models.CharField(max_length=80)),
            ],
            options={
                "db_table": "cod_sis",
            },
        ),
        migrations.CreateModel(
            name="GrupoCliente",
            fields=[
                (
                    "id_grupo",
                    models.AutoField(
                        db_column="id_grupo", primary_key=True, serialize=False
                    ),
                ),
                ("nome", models.CharField(max_length=80)),
            ],
            options={
                "db_table": "grupo_cliente",
            },
        ),
        migrations.CreateModel(
            name="TipoVenda",
            fields=[
                (
                    "id_tipo_venda",
                    models.AutoField(
                        db_column="id_tipo_venda", primary_key=True, serialize=False
                    ),
                ),
                ("nome", models.CharField(max_length=80)),
            ],
            options={
                "db_table": "tipo_venda",
            },
        ),
        migrations.CreateModel(
            name="Fornecedor",
            fields=[
                (
                    "id_fornecedor",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("nome_fornecedor", models.CharField(max_length=120)),
                (
                    "raz_social",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("dt_cadastro", models.DateField(blank=True, null=True)),
                ("codigo", models.CharField(blank=True, default="", max_length=5)),
                ("operador", models.IntegerField(default=0)),
                ("usuario", models.CharField(blank=True, default="", max_length=100)),
                (
                    "id_codsis",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_codsis",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fornecedores",
                        to="cadastros.codsis",
                    ),
                ),
            ],
            options={
                "db_table": "fornecedores",
            },
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id_cliente",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("nome_cliente", models.CharField(max_length=120)),
                (
                    "raz_social",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("prazo_cob", models.IntegerField(default=0)),
                (
                    "id_grupo",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_grupo",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clientes",
                        to="cadastros.grupocliente",
                    ),
                ),
                (
                    "id_tipo_venda",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_tipo_venda",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clientes",
                        to="cadastros.tipovenda",
                    ),
                ),
            ],
            options={
                "db_table": "clientes",
            },
        ),
    ]
