# Generated by Django 5.2.15 on 2026-06-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0002_codsis_grupocliente_tipovenda_fornecedor_cliente"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="operador",
        ),
        migrations.AddField(
            model_name="cliente",
            name="hash_md5",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="fornecedor",
            name="hash_md5",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="produto",
            name="hash_md5",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
