# Generated by Django 5.2.15 on 2026-06-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0004_aliquota_rename_campos_parametros"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateExportacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                ("tabela", models.CharField(max_length=40)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("BASICO", "BASICO"), ("SQL", "SQL")], max_length=10
                    ),
                ),
                ("colunas_selecionadas", models.JSONField(blank=True, null=True)),
                ("query_sql", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "template_exportacao",
                "ordering": ["nome"],
            },
        ),
    ]
