# Generated by Django 5.2.15 on 2026-06-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0005_templateexportacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormaPagamento",
            fields=[
                (
                    "id_forma",
                    models.BigIntegerField(
                        db_column="id_forma", primary_key=True, serialize=False
                    ),
                ),
                ("descricao", models.CharField(max_length=120)),
            ],
            options={
                "db_table": "forma_pagamento",
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id_usuario",
                    models.BigIntegerField(
                        db_column="id_usuario", primary_key=True, serialize=False
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
            ],
            options={
                "db_table": "usuario",
            },
        ),
    ]
