# Generated by Django 5.2.15 on 2026-06-16 18:15

from django.db import migrations, models


def preencher_nome_gerencial(apps, schema_editor):
    Produto = apps.get_model("cadastros", "Produto")
    Produto.objects.filter(nome_gerencial="").update(nome_gerencial=models.F("produto"))


def posicionar_coluna_nome_gerencial(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SHOW COLUMNS FROM produtos LIKE 'nome_gerencial'")
        if cursor.fetchone() is None:
            return

        cursor.execute(
            "ALTER TABLE produtos "
            "MODIFY COLUMN nome_gerencial varchar(120) NOT NULL DEFAULT '' AFTER produto"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0010_produto_ncm"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="nome_gerencial",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.RunPython(
            preencher_nome_gerencial,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            posicionar_coluna_nome_gerencial,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
