# Generated by Django 5.2.15 on 2026-06-16 20:05

from django.db import migrations, models


def preencher_nome_gerencial(apps, schema_editor):
    Cliente = apps.get_model("cadastros", "Cliente")
    Fornecedor = apps.get_model("cadastros", "Fornecedor")

    Cliente.objects.filter(nome_gerencial="").update(nome_gerencial=models.F("nome_cliente"))
    Fornecedor.objects.filter(nome_gerencial="").update(nome_gerencial=models.F("nome_fornecedor"))


def posicionar_colunas_nome_gerencial(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SHOW COLUMNS FROM clientes LIKE 'nome_gerencial'")
        if cursor.fetchone() is not None:
            cursor.execute(
                "ALTER TABLE clientes "
                "MODIFY COLUMN nome_gerencial varchar(120) NOT NULL DEFAULT '' AFTER nome_cliente"
            )

        cursor.execute("SHOW COLUMNS FROM fornecedores LIKE 'nome_gerencial'")
        if cursor.fetchone() is not None:
            cursor.execute(
                "ALTER TABLE fornecedores "
                "MODIFY COLUMN nome_gerencial varchar(120) NOT NULL DEFAULT '' AFTER nome_fornecedor"
            )


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0011_produto_nome_gerencial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="nome_gerencial",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="fornecedor",
            name="nome_gerencial",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.RunPython(
            preencher_nome_gerencial,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            posicionar_colunas_nome_gerencial,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
