# Generated by Django 5.2.15 on 2026-06-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="STG_AuditoriaPlanilha",
            fields=[
                (
                    "id_stg_auditoria_planilha",
                    models.BigAutoField(
                        db_column="id_stg_auditoria_planilha",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data_venda", models.DateField(db_index=True)),
                ("hora_venda", models.TimeField(blank=True, null=True)),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[("NFCE", "NFCe"), ("DAV", "DAV")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("id_legado", models.BigIntegerField(db_index=True)),
                (
                    "usuario_nome",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "cliente_nome",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("valor_total", models.DecimalField(decimal_places=6, max_digits=18)),
                (
                    "tipo_pagamento_descricao",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "status_validacao",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("DIVERGENTE", "Divergente"),
                            ("APROVADO", "Aprovado"),
                        ],
                        db_index=True,
                        default="PENDENTE",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "stg_auditoria_planilha",
            },
        ),
        migrations.CreateModel(
            name="STG_ItemVenda",
            fields=[
                (
                    "id_stg_item_venda",
                    models.BigAutoField(
                        db_column="id_stg_item_venda", primary_key=True, serialize=False
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[("NFCE", "NFCe"), ("DAV", "DAV")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("id_venda_legado", models.BigIntegerField(db_index=True)),
                (
                    "status_venda",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("dia_semana", models.CharField(blank=True, default="", max_length=10)),
                ("data_venda", models.DateField(db_index=True)),
                (
                    "semana_label",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("mes_label", models.CharField(blank=True, default="", max_length=30)),
                ("hora_venda", models.TimeField(blank=True, null=True)),
                ("ref_hora", models.IntegerField(blank=True, null=True)),
                ("id_cliente_legado", models.BigIntegerField(blank=True, null=True)),
                (
                    "nome_cliente_legado",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("item", models.IntegerField(blank=True, null=True)),
                ("id_produto_legado", models.BigIntegerField(db_index=True)),
                (
                    "nome_produto_legado",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "unidade_comercial_legado",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "quantidade",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "valor_total_calculado",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                ("cancelado", models.BooleanField(default=False)),
                ("ncm", models.CharField(blank=True, default="", max_length=20)),
                ("id_usuario_legado", models.BigIntegerField(blank=True, null=True)),
                (
                    "valor_custo",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "valor_total_item",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "status_validacao",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("DIVERGENTE", "Divergente"),
                            ("APROVADO", "Aprovado"),
                        ],
                        db_index=True,
                        default="PENDENTE",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "stg_item_venda",
            },
        ),
        migrations.CreateModel(
            name="STG_PagamentoVenda",
            fields=[
                (
                    "id_stg_pagamento_venda",
                    models.BigAutoField(
                        db_column="id_stg_pagamento_venda",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[("NFCE", "NFCe"), ("DAV", "DAV")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("id_venda_legado", models.BigIntegerField(db_index=True)),
                (
                    "id_tipo_pagamento_legado",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "tipo_pagamento_descricao_legado",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("valor_pago", models.DecimalField(decimal_places=6, max_digits=18)),
                ("estorno", models.BooleanField(default=False)),
                ("nsu", models.CharField(blank=True, default="", max_length=80)),
                ("rede", models.CharField(blank=True, default="", max_length=80)),
                (
                    "status_validacao",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("DIVERGENTE", "Divergente"),
                            ("APROVADO", "Aprovado"),
                        ],
                        db_index=True,
                        default="PENDENTE",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "stg_pagamento_venda",
            },
        ),
        migrations.CreateModel(
            name="STG_Venda",
            fields=[
                (
                    "id_stg_venda",
                    models.BigAutoField(
                        db_column="id_stg_venda", primary_key=True, serialize=False
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[("NFCE", "NFCe"), ("DAV", "DAV")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("id_legado", models.BigIntegerField(db_index=True)),
                (
                    "status_venda",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "nome_computador",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("data_venda", models.DateField(db_index=True)),
                ("hora_venda", models.TimeField(blank=True, null=True)),
                ("ref_hora", models.IntegerField(blank=True, null=True)),
                ("id_cliente_legado", models.BigIntegerField(blank=True, null=True)),
                (
                    "nome_cliente_legado",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("estorno", models.BooleanField(default=False)),
                (
                    "id_tipo_pagamento_legado",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("nsu", models.CharField(blank=True, default="", max_length=80)),
                ("rede", models.CharField(blank=True, default="", max_length=80)),
                (
                    "nfce_status",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "nfce_numero",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "valor_pagamento_legado",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                ("id_usuario_legado", models.BigIntegerField(blank=True, null=True)),
                (
                    "nome_usuario_legado",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "tipo_pagamento_descricao_legado",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "valor_venda",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "valor_final",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "status_validacao",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("DIVERGENTE", "Divergente"),
                            ("APROVADO", "Aprovado"),
                        ],
                        db_index=True,
                        default="PENDENTE",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "stg_venda",
            },
        ),
    ]
