# Generated by Django 5.2.15 on 2026-06-07 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validacao", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stg_itemvenda",
            name="stg_venda",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itens",
                to="validacao.stg_venda",
            ),
        ),
        migrations.AddField(
            model_name="stg_pagamentovenda",
            name="stg_venda",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pagamentos",
                to="validacao.stg_venda",
            ),
        ),
    ]
