# Generated by Django 5.2.15 on 2026-06-07 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("validacao", "0002_stg_itemvenda_stg_venda_stg_pagamentovenda_stg_venda"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stg_itemvenda",
            name="dia_semana",
        ),
        migrations.RemoveField(
            model_name="stg_itemvenda",
            name="item",
        ),
        migrations.RemoveField(
            model_name="stg_itemvenda",
            name="mes_label",
        ),
        migrations.RemoveField(
            model_name="stg_itemvenda",
            name="ref_hora",
        ),
        migrations.RemoveField(
            model_name="stg_itemvenda",
            name="semana_label",
        ),
        migrations.RemoveField(
            model_name="stg_itemvenda",
            name="valor_custo",
        ),
        migrations.RemoveField(
            model_name="stg_itemvenda",
            name="valor_total_item",
        ),
        migrations.RemoveField(
            model_name="stg_venda",
            name="id_tipo_pagamento_legado",
        ),
        migrations.RemoveField(
            model_name="stg_venda",
            name="ref_hora",
        ),
        migrations.RemoveField(
            model_name="stg_venda",
            name="tipo_pagamento_descricao_legado",
        ),
        migrations.RemoveField(
            model_name="stg_venda",
            name="valor_pagamento_legado",
        ),
        migrations.RemoveField(
            model_name="stg_venda",
            name="valor_venda",
        ),
    ]
