# Generated by Django 5.2.15 on 2026-06-07 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("validacao", "0003_remove_stg_itemvenda_dia_semana_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stg_itemvenda",
            name="id_usuario_legado",
        ),
    ]
