# Generated by Django 5.2.15 on 2026-07-23 17:58

import django.db.models.deletion
from django.db import migrations, models

_MOTIVOS_VALIDOS = {"divergencia_totais", "divergencia_formato", "duplicado_sot"}


def _popular_motivos_do_snapshot(apps, schema_editor):
    """Popula STG_VendaMotivoDivergencia a partir dos snapshots existentes."""
    STG_Venda = apps.get_model("validacao", "STG_Venda")
    STG_VendaMotivoDivergencia = apps.get_model("validacao", "STG_VendaMotivoDivergencia")

    novos = []
    for venda in STG_Venda.objects.filter(status_validacao="DIVERGENTE").iterator(chunk_size=500):
        snapshot = venda.snapshot_divergencia or {}
        for motivo in snapshot.get("motivos") or []:
            motivo_norm = str(motivo).strip().lower()
            if motivo_norm in _MOTIVOS_VALIDOS:
                novos.append(
                    STG_VendaMotivoDivergencia(stg_venda_id=venda.pk, motivo=motivo_norm)
                )

    if novos:
        STG_VendaMotivoDivergencia.objects.bulk_create(novos, batch_size=2000, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ("validacao", "0005_stg_venda_tratamento_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stg_venda",
            name="status_tratamento",
            field=models.CharField(
                choices=[
                    ("PENDENTE", "Pendente"),
                    ("AJUSTADO", "Ajustado"),
                    ("VALIDADO", "Validado"),
                    ("NEGLIGENCIADO", "Negligenciado"),
                ],
                db_index=True,
                default="PENDENTE",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="STG_VendaMotivoDivergencia",
            fields=[
                (
                    "id_stg_venda_motivo",
                    models.BigAutoField(
                        db_column="id_stg_venda_motivo",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        choices=[
                            ("divergencia_totais", "Divergência de totais"),
                            ("divergencia_formato", "Divergência de formato"),
                            ("duplicado_sot", "Duplicado no SOT"),
                        ],
                        db_index=True,
                        max_length=60,
                    ),
                ),
                (
                    "stg_venda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="motivos",
                        to="validacao.stg_venda",
                    ),
                ),
            ],
            options={
                "db_table": "stg_venda_motivo_divergencia",
                "unique_together": {("stg_venda", "motivo")},
            },
        ),
        migrations.RunPython(
            _popular_motivos_do_snapshot,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
