# Generated by Django 5.2.15 on 2026-07-24 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validacao", "0006_add_stg_venda_motivo_divergencia"),
    ]

    operations = [
        migrations.AddField(
            model_name="stg_venda",
            name="importacao_id",
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="stg_venda",
            name="importacao_origem",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
