# Generated by Django 5.2.15 on 2026-07-29 00:49

from django.db import migrations, models


def migrar_status_para_modelo_simplificado(apps, schema_editor):
    STG_Venda = apps.get_model("validacao", "STG_Venda")

    # APROVADO + PENDENTE → APROVADO + AUTOMATICO
    STG_Venda.objects.filter(status_validacao="APROVADO", status_tratamento="PENDENTE").update(
        status_tratamento="AUTOMATICO"
    )
    # APROVADO + VALIDADO → APROVADO + MANUAL
    STG_Venda.objects.filter(status_validacao="APROVADO", status_tratamento="VALIDADO").update(
        status_tratamento="MANUAL"
    )
    # APROVADO + AJUSTADO → APROVADO + MANUAL
    STG_Venda.objects.filter(status_validacao="APROVADO", status_tratamento="AJUSTADO").update(
        status_tratamento="MANUAL"
    )
    # APROVADO + NEGLIGENCIADO → NEGADO + MANUAL
    STG_Venda.objects.filter(status_validacao="APROVADO", status_tratamento="NEGLIGENCIADO").update(
        status_validacao="NEGADO", status_tratamento="MANUAL"
    )
    # DIVERGENTE + PENDENTE → PENDENTE + PENDENTE
    STG_Venda.objects.filter(status_validacao="DIVERGENTE", status_tratamento="PENDENTE").update(
        status_validacao="PENDENTE"
    )
    # DIVERGENTE + AJUSTADO → APROVADO + MANUAL
    STG_Venda.objects.filter(status_validacao="DIVERGENTE", status_tratamento="AJUSTADO").update(
        status_validacao="APROVADO", status_tratamento="MANUAL"
    )
    # DIVERGENTE + VALIDADO → APROVADO + MANUAL
    STG_Venda.objects.filter(status_validacao="DIVERGENTE", status_tratamento="VALIDADO").update(
        status_validacao="APROVADO", status_tratamento="MANUAL"
    )
    # DIVERGENTE + NEGLIGENCIADO → NEGADO + MANUAL
    STG_Venda.objects.filter(status_validacao="DIVERGENTE", status_tratamento="NEGLIGENCIADO").update(
        status_validacao="NEGADO", status_tratamento="MANUAL"
    )
    # PENDENTE + PENDENTE permanece PENDENTE + PENDENTE (não processado ainda)


class Migration(migrations.Migration):

    dependencies = [
        ("validacao", "0007_stg_venda_importacao_id_stg_venda_importacao_origem"),
    ]

    operations = [
        migrations.RunPython(
            migrar_status_para_modelo_simplificado,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="stg_venda",
            name="validacao_override",
        ),
        migrations.AlterField(
            model_name="stg_auditoriaplanilha",
            name="status_validacao",
            field=models.CharField(
                choices=[
                    ("PENDENTE", "Pendente"),
                    ("APROVADO", "Aprovado"),
                    ("NEGADO", "Negado"),
                ],
                db_index=True,
                default="PENDENTE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="stg_itemvenda",
            name="status_validacao",
            field=models.CharField(
                choices=[
                    ("PENDENTE", "Pendente"),
                    ("APROVADO", "Aprovado"),
                    ("NEGADO", "Negado"),
                ],
                db_index=True,
                default="PENDENTE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="stg_pagamentovenda",
            name="status_validacao",
            field=models.CharField(
                choices=[
                    ("PENDENTE", "Pendente"),
                    ("APROVADO", "Aprovado"),
                    ("NEGADO", "Negado"),
                ],
                db_index=True,
                default="PENDENTE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="stg_venda",
            name="status_tratamento",
            field=models.CharField(
                choices=[
                    ("PENDENTE", "Pendente"),
                    ("AUTOMATICO", "Automatico"),
                    ("MANUAL", "Manual"),
                ],
                db_index=True,
                default="PENDENTE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="stg_venda",
            name="status_validacao",
            field=models.CharField(
                choices=[
                    ("PENDENTE", "Pendente"),
                    ("APROVADO", "Aprovado"),
                    ("NEGADO", "Negado"),
                ],
                db_index=True,
                default="PENDENTE",
                max_length=20,
            ),
        ),
    ]
