# Generated by Django 5.2.15 on 2026-10-06 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0013_planoconta_codigo_ordenacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidade', models.CharField(max_length=30)),
                ('entidade_id', models.BigIntegerField()),
                ('acao', models.CharField(max_length=40)),
                ('antes', models.JSONField(default=dict)),
                ('depois', models.JSONField(default=dict)),
                ('operador', models.CharField(blank=True, default='', max_length=120)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoteDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='despesas/lotes/%Y/%m/')),
                ('hash_sha256', models.CharField(max_length=64)),
                ('status', models.CharField(default='VALIDADO', max_length=20)),
                ('total_linhas', models.PositiveIntegerField(default=0)),
                ('prontas', models.PositiveIntegerField(default=0)),
                ('pendentes', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=220)),
                ('chave', models.CharField(max_length=220, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('codigo_origem', models.CharField(blank=True, default='', max_length=60)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('caminho', models.CharField(max_length=750, unique=True)),
                ('nivel', models.PositiveSmallIntegerField()),
                ('codigo_origem', models.CharField(blank=True, default='', max_length=60)),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filhas', to='despesas.categoriadespesa')),
            ],
            options={
                'ordering': ['caminho'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_origem', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('origem', models.CharField(choices=[('MANUAL', 'Manual'), ('XLSX', 'Planilha')], default='MANUAL', max_length=12)),
                ('fornecedor_texto', models.CharField(blank=True, default='', max_length=220)),
                ('documento', models.CharField(blank=True, default='', max_length=120)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('emissao', models.DateField(blank=True, null=True)),
                ('vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=18)),
                ('campos_manuais', models.JSONField(blank=True, default=list)),
                ('dados_origem', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.fornecedor')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='despesas.tipodespesa')),
            ],
        ),
        migrations.CreateModel(
            name='LinhaDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('id_origem', models.CharField(blank=True, default='', max_length=120)),
                ('dados', models.JSONField(default=dict)),
                ('erros', models.JSONField(default=list)),
                ('status', models.CharField(default='PENDENTE', max_length=20)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas', to='despesas.lotedespesa')),
                ('movimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='despesas.movimentodespesa')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='despesas.tipodespesa')),
            ],
        ),
        migrations.CreateModel(
            name='PagamentoDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_origem', models.CharField(blank=True, max_length=145, null=True, unique=True)),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=18)),
                ('forma', models.CharField(blank=True, default='', max_length=80)),
                ('origem', models.CharField(choices=[('MANUAL', 'Manual'), ('XLSX', 'Planilha')], default='MANUAL', max_length=12)),
                ('campos_manuais', models.JSONField(blank=True, default=list)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('movimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='despesas.movimentodespesa')),
            ],
        ),
        migrations.CreateModel(
            name='SnapshotDespesaMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField()),
                ('base', models.CharField(choices=[('VENCIMENTO', 'Obrigações'), ('PAGAMENTO', 'Saídas')], max_length=12)),
                ('status', models.CharField(default='PENDENTE', max_length=12)),
                ('atualizado_em', models.DateTimeField(blank=True, null=True)),
                ('erro', models.TextField(blank=True, default='')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('mes', 'base'), name='despesa_snapshot_mes_base')],
            },
        ),
        migrations.CreateModel(
            name='AgregadoDespesaMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField()),
                ('base', models.CharField(choices=[('VENCIMENTO', 'Obrigações'), ('PAGAMENTO', 'Saídas')], max_length=12)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='despesas.tipodespesa')),
            ],
        ),
        migrations.CreateModel(
            name='VinculoTipoDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_familia', to='despesas.categoriadespesa')),
                ('folha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_vinculados', to='despesas.categoriadespesa')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='despesas.tipodespesa')),
            ],
        ),
        migrations.CreateModel(
            name='ConflitoDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=50)),
                ('valor_atual', models.JSONField(blank=True, null=True)),
                ('valor_origem', models.JSONField(blank=True, null=True)),
                ('resolvido', models.BooleanField(default=False)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='despesas.linhadespesa')),
                ('movimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflitos', to='despesas.movimentodespesa')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('linha', 'campo'), name='despesa_conflito_linha_campo_unico')],
            },
        ),
        migrations.AddConstraint(
            model_name='linhadespesa',
            constraint=models.UniqueConstraint(fields=('lote', 'numero'), name='despesa_lote_linha_unica'),
        ),
        migrations.AddConstraint(
            model_name='agregadodespesamensal',
            constraint=models.UniqueConstraint(fields=('mes', 'tipo', 'base'), name='despesa_agregado_mes_tipo_base'),
        ),
        migrations.AddConstraint(
            model_name='vinculotipodespesa',
            constraint=models.UniqueConstraint(fields=('tipo', 'familia'), name='despesa_tipo_familia_unica'),
        ),
    ]
