# Generated by Django 5.2.15 on 2026-10-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentodespesa',
            name='chave_base',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
