# Generated by Django 5.2.15 on 2026-10-07 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0004_lotedespesa_chave_ativa"),
    ]

    operations = [
        migrations.AddField(
            model_name="snapshotdespesamensal",
            name="diario_atualizado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="AgregadoDespesaDiario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dia", models.DateField()),
                (
                    "base",
                    models.CharField(
                        choices=[("VENCIMENTO", "Obrigações"), ("PAGAMENTO", "Saídas")],
                        max_length=12,
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="despesas.tipodespesa",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["base", "dia"], name="despesa_diario_base_dia")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dia", "tipo", "base"),
                        name="despesa_agregado_dia_tipo_base",
                    )
                ],
            },
        ),
    ]
