# Generated by Django 5.2.15 on 2026-06-06 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cadastros", "0006_formapagamento_usuario"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venda",
            fields=[
                (
                    "id_venda",
                    models.BigAutoField(
                        db_column="id_venda", primary_key=True, serialize=False
                    ),
                ),
                ("id_legado", models.BigIntegerField(db_index=True)),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[("NFCE", "NFCe"), ("DAV", "DAV")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("data_venda", models.DateField(db_index=True)),
                ("hora_venda", models.TimeField(blank=True, null=True)),
                (
                    "valor_total_documento",
                    models.DecimalField(decimal_places=6, max_digits=18),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_cliente",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendas",
                        to="cadastros.cliente",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        db_column="id_usuario",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendas",
                        to="cadastros.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "venda",
            },
        ),
        migrations.CreateModel(
            name="PagamentoVenda",
            fields=[
                (
                    "id_pagamento_venda",
                    models.BigAutoField(
                        db_column="id_pagamento_venda",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("valor_pago", models.DecimalField(decimal_places=6, max_digits=18)),
                (
                    "forma_pagamento",
                    models.ForeignKey(
                        db_column="id_forma",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagamentos_venda",
                        to="cadastros.formapagamento",
                    ),
                ),
                (
                    "venda",
                    models.ForeignKey(
                        db_column="id_venda",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagamentos",
                        to="vendas.venda",
                    ),
                ),
            ],
            options={
                "db_table": "pagamento_venda",
            },
        ),
        migrations.CreateModel(
            name="ItemVenda",
            fields=[
                (
                    "id_item_venda",
                    models.BigAutoField(
                        db_column="id_item_venda", primary_key=True, serialize=False
                    ),
                ),
                ("quantidade", models.DecimalField(decimal_places=6, max_digits=18)),
                (
                    "valor_unitario",
                    models.DecimalField(decimal_places=6, max_digits=18),
                ),
                (
                    "valor_total_item",
                    models.DecimalField(decimal_places=6, max_digits=18),
                ),
                ("cancelado", models.BooleanField(default=False)),
                (
                    "produto",
                    models.ForeignKey(
                        db_column="id_produto",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens_venda",
                        to="cadastros.produto",
                    ),
                ),
                (
                    "venda",
                    models.ForeignKey(
                        db_column="id_venda",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="vendas.venda",
                    ),
                ),
            ],
            options={
                "db_table": "item_venda",
            },
        ),
        migrations.AddConstraint(
            model_name="venda",
            constraint=models.UniqueConstraint(
                fields=("id_legado", "tipo_documento"), name="uniq_venda_legado_tipo"
            ),
        ),
    ]
