# Generated by Django 5.2.15 on 2026-06-10 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0002_venda_status_pagamento_estorno_item_unidade"),
    ]

    operations = [
        migrations.AddField(
            model_name="venda",
            name="momento_consolidacao",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
