# Generated by Django 5.2.15 on 2026-07-24 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0003_venda_momento_consolidacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="venda",
            name="importacao_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="venda",
            name="importacao_origem",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="venda",
            name="nfce_numero",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="venda",
            name="nfce_status",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
    ]
