# Generated by Django 5.2.15 on 2026-06-12 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cadastros", "0009_cliente_cliente_padrao"),
    ]

    operations = [
        migrations.CreateModel(
            name="Compra",
            fields=[
                (
                    "id_compra",
                    models.BigAutoField(
                        db_column="id_compra", primary_key=True, serialize=False
                    ),
                ),
                ("id_legado", models.BigIntegerField(db_index=True)),
                ("nota", models.BigIntegerField(blank=True, db_index=True, null=True)),
                ("data_emissao", models.DateField(db_index=True)),
                ("data_lanc", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "valor_produtos",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "valor_total_documento",
                    models.DecimalField(decimal_places=6, max_digits=18),
                ),
                ("nfe_status", models.CharField(blank=True, default="", max_length=40)),
                ("momento_consolidacao", models.DateTimeField(blank=True, null=True)),
                (
                    "fornecedor",
                    models.ForeignKey(
                        db_column="id_fornecedor",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compras",
                        to="cadastros.fornecedor",
                    ),
                ),
            ],
            options={
                "db_table": "compra",
            },
        ),
        migrations.CreateModel(
            name="ItemCompra",
            fields=[
                (
                    "id_item_compra",
                    models.BigAutoField(
                        db_column="id_item_compra", primary_key=True, serialize=False
                    ),
                ),
                ("quantidade", models.DecimalField(decimal_places=6, max_digits=18)),
                ("valor_custo", models.DecimalField(decimal_places=6, max_digits=18)),
                (
                    "valor_total_item",
                    models.DecimalField(decimal_places=6, max_digits=18),
                ),
                (
                    "descricao_origem",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "descricao_compra_origem",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "compra",
                    models.ForeignKey(
                        db_column="id_compra",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="compras.compra",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        db_column="id_produto",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens_compra",
                        to="cadastros.produto",
                    ),
                ),
                (
                    "unidade_medida",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_und_medida",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="itens_compra",
                        to="cadastros.unidademedida",
                    ),
                ),
            ],
            options={
                "db_table": "item_compra",
            },
        ),
        migrations.CreateModel(
            name="STG_Compra",
            fields=[
                (
                    "status_validacao",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("DIVERGENTE", "Divergente"),
                            ("APROVADO", "Aprovado"),
                        ],
                        db_index=True,
                        default="PENDENTE",
                        max_length=20,
                    ),
                ),
                (
                    "id_stg_compra",
                    models.BigAutoField(
                        db_column="id_stg_compra", primary_key=True, serialize=False
                    ),
                ),
                ("id_compra_legado", models.BigIntegerField(db_index=True)),
                ("nota", models.BigIntegerField(blank=True, db_index=True, null=True)),
                (
                    "id_fornecedor_legado",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "nome_fornecedor_legado",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("data_emissao", models.DateField(db_index=True)),
                ("data_lanc", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "valor_produtos",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                ("nfe_status", models.CharField(blank=True, default="", max_length=40)),
                (
                    "status_tratamento",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("AJUSTADO", "Ajustado"),
                            ("VALIDADO", "Validado"),
                            ("NEGLIGENCIADO", "Negligenciado"),
                        ],
                        db_index=True,
                        default="PENDENTE",
                        max_length=20,
                    ),
                ),
                ("validacao_override", models.BooleanField(default=False)),
                ("snapshot_divergencia", models.JSONField(blank=True, default=dict)),
                (
                    "tratamento_atualizado_em",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "fornecedor_resolvido",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_fornecedor_resolvido",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stg_compras_resolvidas",
                        to="cadastros.fornecedor",
                    ),
                ),
            ],
            options={
                "db_table": "stg_compra",
            },
        ),
        migrations.CreateModel(
            name="STG_ItemCompra",
            fields=[
                (
                    "status_validacao",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("DIVERGENTE", "Divergente"),
                            ("APROVADO", "Aprovado"),
                        ],
                        db_index=True,
                        default="PENDENTE",
                        max_length=20,
                    ),
                ),
                (
                    "id_stg_item_compra",
                    models.BigAutoField(
                        db_column="id_stg_item_compra",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "id_item_legado",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("id_compra_legado", models.BigIntegerField(db_index=True)),
                (
                    "id_produto_legado",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "nome_produto_legado",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "unidade_legado",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "descricao_legado",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "descricao_compra_legado",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "quantidade",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "valor_custo",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "valor_total_legado",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "valor_total_calculado",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "produto_resolvido",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_produto_resolvido",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stg_itens_compra_resolvidos",
                        to="cadastros.produto",
                    ),
                ),
                (
                    "stg_compra",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_stg_compra",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="compras.stg_compra",
                    ),
                ),
                (
                    "unidade_resolvida",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_und_medida_resolvida",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stg_itens_compra_resolvidos",
                        to="cadastros.unidademedida",
                    ),
                ),
            ],
            options={
                "db_table": "stg_item_compra",
            },
        ),
        migrations.AddConstraint(
            model_name="compra",
            constraint=models.UniqueConstraint(
                fields=("id_legado",), name="uniq_compra_id_legado"
            ),
        ),
    ]
